### PR TITLE
Add GraphQL PHP project

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi @ruudk , thanks for the link.
Could you share the AST part of this project? It does not seems from README and I could not find it any docs there.

This repository should mainly include projects where AST is the root of the project. If the feature is used just marginally, it might distract from the main focus - bring the AST-centered projects to wide group of developers.

**Comment by ruudk** [comment]
https://github.com/webonyx/graphql-php/tree/master/src/Language
https://github.com/webonyx/graphql-php/tree/master/src/Validator

It constructs the whole GraphQL schema document with it and then has dumpers for GraphQL + JSON format.
It uses it again to parse incoming requests and validate them using visitors.

Now looking at the codebase I think that at least half of it is AST related.

**Comment by TomasVotruba** [comment]
I see. Could you share a docs on how to use it for AST node traversing? 
Something like php-parser has for PHP: https://github.com/nikic/PHP-Parser/blob/master/doc/component/Walking_the_AST.markdown

**Comment by ruudk** [comment]
Does this help? https://webonyx.github.io/graphql-php/class-reference/#graphqlutilsast-methods

**Comment by TomasVotruba** [comment]
Thanks, a little, as it looks like code itself. How much would you say this feature is used?

**Comment by ruudk** [comment]
I don't know.... I thought this project was a good example to add but apparently you don't agree.. Let's close this then :)

**Comment by TomasVotruba** [comment]
It feels like focus of this tool is on GraphQL :). This awesome list should have AST in the center of the package.

**Pull request closed without merging**
