### PR TITLE
Add `Infection` to the list

### PR DESCRIPTION
**Pull request by maks-rafalko**
Analyzing and code construction of Mutants are based on PHP-Parser

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you for contribution.

This repository should mainly include projects where AST is the main feature of the project. Not list of package that run on php-parser. If the feature is used just marginally, it might distract from the main focus - bring the AST-centered projects to wide group of developers.

**Comment by maks-rafalko** [comment]
Hm.. I've decided to open this PR after I saw Deptrac here (https://github.com/qossmic/deptrac). From this point of view, I see no difference between Deptrac and Infection - they both use PHP-Parser :)

Infection uses AST a lot - this was the main feature why it superseded Humbug back in 2018 - because of AST and new fresh look.

The main idea of AST usage here is to manipulate the code and generate those Mutants (new versions of source code).

---

Anyway, if you think it's not related to this repository - feel free to close it. Thanks :)

**Comment by TomasVotruba** [comment]
> Hm.. I've decided to open this PR after I saw Deptrac here ([qossmic/deptrac](https://github.com/qossmic/deptrac)). From this point of view, I see no difference between Deptrac and Infection - they both use PHP-Parser :)

If that's the main motivation, we should rethink adding it, as that's missleading :)

> The main idea of AST usage here is to manipulate the code and generate those Mutants (new versions of source code).

I see. Is it something end-user oftens get int contact with? E.g. when you use PHPStan, you work with nodes directly in the PHPStan rule. There is no other way around it. PHPStan also uses parallel processes, but I don't think it's a good additiona to "awesome parallel".

**Comment by TomasVotruba** [comment]
Thanks to your feedback I've updated the description and removed deptract: https://github.com/TomasVotruba/awesome-php-ast/commit/ef15734a472401d38af94f0362602e1eac1ce0b8

:+1: 

I'm checking the config and manual for Infectoin - https://infection.github.io/guide/usage.html, and it seems the similar case. I'm affraid it's not related to this repository and have to pass. Thanks for understanding :pray:

**Pull request closed without merging**
